### ISSUE TITLE
VSCode does not show suggestions for es6 import style?

### ISSUE THREAD

**Issue by Nikki1993** [electron/electron-typescript-definitions#65] opened 2017-06-25 08:42 UTC
When I write `import {} from 'electron'` it doesn't give me import suggestions, however if I write is as a standard node module import `const {} = require('electron')` I get suggestions to import; app, BrowserWindow etc, any guesses where is it going south?

Steps to Reproduce:

1. Download vscode 
2. Create new project with `yarn init`
3. Run `yarn install electron`
4. Create new .ts file and try to import electron module and get suggestions about exported modules via `import {} from 'electron`

**Comment by zeke** [comment] 2017-06-27 19:33
<kbd>Ctrl</kbd><kbd>Space</kbd> might help...

<img width="593" alt="screen shot 2017-06-27 at 12 32 37 pm" src="https://user-images.githubusercontent.com/2289/27606370-d5abb51e-5b34-11e7-9949-540fcc2e0ea1.png">

**Comment by Nikki1993** [comment] 2017-06-27 19:41
Obviously @zeke but I did that and it doesn't work for me. Even with all extensions disabled, no suggestions have been showed for es6 import style.

**Comment by mjbvz** [comment] 2017-06-28 03:18
I believe the root cause of this issue is [this TS bug]( https://github.com/Microsoft/TypeScript/issues/16610), rather than an error in the electron `d.ts` file. See my comment on the VSCode mirror of this issue for more info: https://github.com/Microsoft/vscode/issues/29399#issuecomment-311545226

**Comment by zeke** [comment] 2017-06-28 19:19
Thanks @mjbvz. Closing this out.

**Closed by zeke** 2017-06-28 19:19 UTC
